"""学习计划 → .ics 日历文件 —— v19 第三梯队 #13-A。

设计：
- 零外部依赖（手写 RFC 5545 输出，不依赖 ics 库）
- 一门课 = 一个 VEVENT，每天一条全天事件
- 描述包含：第几天 / 任务 / 关联章节
- 时间从今天开始逐天推进（默认 7 天，可按 plan 长度自适应）
- 输出：Google Calendar / 苹果日历 / Outlook 都能直接导入

输入格式（run_plan_pipeline 返回的 result）——**两种 plan 形态都要吃下**：

1) 真实 pipeline 输出（agents/writer.py）是**字符串列表**：
   {
       "course": "Python 入门",
       "plan": [
           "第1天：通读章节内容，标记不懂的概念——环境搭建 与 基础语法",
           "第2天：看配套视频课程，对照笔记补全关键点——基础语法 与 控制流程",
           ...
       ]
   }

2) 早期/测试用的结构化 dict 列表：
   {
       "course": "Python 入门",
       "plan": [
           {"day": 1, "title": "...", "tasks": ["..."], "chapters": ["..."]},
           ...
       ]
   }

形态 1 由 `_normalize_day` 归一化成形态 2 再渲染，
**绝不能对字符串静默 continue**——那样导出的 .ics 会是 0 个事件（空的）。
"""

from __future__ import annotations

import datetime as _dt
import os
import re
import uuid

# plan 归一化：字符串 / dict 两种形态统一（progress_store / markdown_export 共用）
# 保留 `_normalize_day` / `_normalize_plan` 别名，向后兼容旧引用。
from tools.plan_normalize import (
    normalize_day as _normalize_day,
    normalize_plan as _normalize_plan,
)

# ============================================================
# ICS 文本转义（RFC 5545 § 3.3.11）
# ============================================================
def _escape_ics(text: str) -> str:
    """转义 ICS 描述里的特殊字符。"""
    if text is None:
        return ""
    text = str(text)
    # 顺序：反斜杠 → 逗号 → 分号 → 换行
    text = text.replace("\\", "\\\\")
    text = text.replace(",", "\\,")
    text = text.replace(";", "\\;")
    text = text.replace("\r\n", "\\n")
    text = text.replace("\n", "\\n")
    return text


def _fold_line(line: str, max_len: int = 75) -> str:
    """RFC 5545 行折叠：超过 75 字节的行需折行。

    注：折行时后续行以单空格开头。
    """
    # 把 UTF-8 字节长度算上 —— 中文是 3 字节/字
    encoded = line.encode("utf-8")
    if len(encoded) <= max_len:
        return line

    out = []
    # 用字符遍历，避免切坏多字节字符
    cur_bytes = 0
    cur_str = ""
    for ch in line:
        ch_bytes = len(ch.encode("utf-8"))
        if cur_bytes + ch_bytes > max_len and cur_str:
            out.append(cur_str)
            cur_str = " " + ch   # 续行以单空格开头
            cur_bytes = len(cur_str.encode("utf-8"))
        else:
            cur_str += ch
            cur_bytes += ch_bytes
    if cur_str:
        out.append(cur_str)
    return "\r\n".join(out)


# ============================================================
# 日期工具
# ============================================================
def _parse_date(s: str | None) -> _dt.date | None:
    """解析 'YYYY-MM-DD' 或 None。"""
    if not s:
        return None
    s = str(s).strip()
    for fmt in ("%Y-%m-%d", "%Y/%m/%d", "%Y.%m.%d"):
        try:
            return _dt.datetime.strptime(s, fmt).date()
        except Exception:
            continue
    return None


def _fmt_ics_date(d: _dt.date) -> str:
    """日期 → YYYYMMDD（VALUE=DATE 格式）。"""
    return d.strftime("%Y%m%d")


def _fmt_ics_datetime(dt: _dt.datetime) -> str:
    """UTC 时间 → YYYYMMDDTHHMMSSZ。"""
    return dt.strftime("%Y%m%dT%H%M%SZ")


def _dtstamp() -> str:
    """当前 UTC 时间戳（DTSTAMP 字段）。"""
    # 用 timezone-aware 替代 datetime.utcnow()（Python 3.12+ deprecate）
    now = _dt.datetime.now(_dt.timezone.utc)
    return _fmt_ics_datetime(now)


# ============================================================
# 单个 plan day → VEVENT
# ============================================================
def _render_day_event(
    day_idx: int,
    day_data: dict,
    start_date: _dt.date,
    course: str,
    duration_days: int = 1,
) -> str:
    """生成一条 VEVENT 字符串。"""
    # 日期 = start_date + (day_idx - 1)
    event_date = start_date + _dt.timedelta(days=day_idx - 1)
    # end_date 是 VALUE=DATE 时的次日（RFC 5545：DTEND 排他）
    end_date = event_date + _dt.timedelta(days=duration_days)

    title = day_data.get("title") or day_data.get("name") or f"第 {day_idx} 天"
    tasks = day_data.get("tasks") or []
    chapters = day_data.get("chapters") or day_data.get("chapter") or []

    # 描述组装
    desc_parts = [f"Day {day_idx} · {title}"]
    if tasks:
        if isinstance(tasks, list):
            desc_parts.append("Tasks:")
            desc_parts.extend(f"  • {t}" for t in tasks)
        else:
            desc_parts.append(f"Tasks: {tasks}")
    if chapters:
        if isinstance(chapters, list):
            desc_parts.append("Chapters:")
            desc_parts.extend(f"  • {c}" for c in chapters)
        else:
            desc_parts.append(f"Chapters: {chapters}")
    desc_parts.append("")
    desc_parts.append(f"Course: {course}")
    desc_parts.append("Generated by study-liu")

    summary = f"[{course}] Day {day_idx}: {title}"

    # 拼接 VEVENT
    lines = [
        "BEGIN:VEVENT",
        f"UID:{uuid.uuid4()}@study-liu",
        f"DTSTAMP:{_dtstamp()}",
        f"DTSTART;VALUE=DATE:{_fmt_ics_date(event_date)}",
        f"DTEND;VALUE=DATE:{_fmt_ics_date(end_date)}",
        f"SUMMARY:{_escape_ics(summary)}",
        f"DESCRIPTION:{_escape_ics(chr(10).join(desc_parts))}",
        "TRANSP:TRANSPARENT",   # 不占用时间（让日历只显示日期）
        "BEGIN:VALARM",
        "ACTION:DISPLAY",
        "DESCRIPTION:今天要学习哦",
        "TRIGGER:-P1D",         # 提前 1 天提醒
        "END:VALARM",
        "END:VEVENT",
    ]
    return "\r\n".join(_fold_line(l) for l in lines)


# ============================================================
# 主入口
# ============================================================
def render_ics(
    result: dict,
    start_date: str | None = None,
    course: str | None = None,
    timezone_name: str = "UTC",
) -> str:
    """把 run_plan_pipeline 的 result 转成完整 ICS 文本。

    Args:
        result: 完整 result dict（必须含 plan 字段）
        start_date: 起始日期 'YYYY-MM-DD'，默认今天
        course: 课程名（默认从 result 取）
        timezone_name: 时区名（写入 X-WR-TIMEZONE）

    Returns:
        完整 ICS 字符串（CRLF 行结尾，UTF-8）
    """
    if not isinstance(result, dict):
        raise ValueError("result 必须是 dict")

    course = course or result.get("course") or "学习计划"
    plan = result.get("plan") or []
    if not isinstance(plan, list):
        raise ValueError("plan 必须是 list")

    # 起始日期：今天（如果没指定）
    if start_date:
        sd = _parse_date(start_date)
        if sd is None:
            raise ValueError(f"start_date 格式错误：{start_date}")
    else:
        sd = _dt.date.today()

    # 日历头
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//study-liu//CN//ZH",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:{_escape_ics(f'{course} 学习计划')}",
        f"X-WR-TIMEZONE:{_escape_ics(timezone_name)}",
    ]

    # 每一天一个 VEVENT
    # 注意：plan 在真实 pipeline 里是**字符串列表**，必须先归一化再渲染。
    # 早期版本对非 dict 直接 continue，导致导出的 .ics 一个事件都没有（空日历）。
    for norm in _normalize_plan(plan, skip_blank=True):
        day_no = norm.get("day") or 1
        lines.append(_render_day_event(day_no, norm, sd, course))

    lines.append("END:VCALENDAR")
    return "\r\n".join(lines) + "\r\n"


def suggest_ics_filename(course: str) -> str:
    """生成安全的 .ics 文件名。"""
    safe = re.sub(r"[\\/:*?\"<>|\s]+", "_", (course or "study").strip())
    safe = safe.strip("_.") or "study"
    return f"{safe}_学习计划.ics"


def export_plan_to_ics(
    result: dict,
    target_path: str,
    start_date: str | None = None,
) -> str:
    """生成 ICS 并写入文件。

    Returns:
        写入的文件路径（绝对路径）
    """
    content = render_ics(result, start_date=start_date)
    target_dir = os.path.dirname(os.path.abspath(target_path))
    os.makedirs(target_dir, exist_ok=True)
    with open(target_path, "w", encoding="utf-8", newline="") as f:
        f.write(content)
    return os.path.abspath(target_path)


def count_events(ics_text: str) -> int:
    """统计 ICS 中 VEVENT 数量（用于测试 + UI 提示）。"""
    return len(re.findall(r"BEGIN:VEVENT", ics_text))